# serieA-Predicition-Model

In [1]:
import pandas as pd
import numpy as np

In [2]:
players = pd.read_csv('tables/players.csv')
seriea_players = players[(players.current_club_domestic_competition_id == 'IT1') & (players.last_season > 2024)]
seriea_players

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
1299,15452,Raúl,Albiol,Raúl Albiol,2025,4172,raul-albiol,Spain,Vilamarxant,Spain,...,LP Sport Management,https://img.a.transfermarkt.technology/portrai...,58.0,0.0,NaN,https://www.transfermarkt.co.uk/raul-albiol/pr...,IT1,Pisa Sporting Club,800000.0,18000000.0
2342,27807,Daniele,Padelli,Daniele Padelli,2025,410,daniele-padelli,Italy,Lecco,Italy,...,Mondial,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,NaN,https://www.transfermarkt.co.uk/daniele-padell...,IT1,Udinese Calcio,150000.0,2000000.0
2354,27992,Luka,Modrić,Luka Modrić,2025,5,luka-modric,Jugoslawien (SFR),Zadar,Croatia,...,NaN,https://img.a.transfermarkt.technology/portrai...,198.0,29.0,NaN,https://www.transfermarkt.co.uk/luka-modric/pr...,IT1,Associazione Calcio Milan,4000000.0,55000000.0
2757,33571,Lorenzo,De Silvestri,Lorenzo De Silvestri,2025,1025,lorenzo-de-silvestri,Italy,Roma,Italy,...,Sergio Berti,https://img.a.transfermarkt.technology/portrai...,6.0,0.0,NaN,https://www.transfermarkt.co.uk/lorenzo-de-sil...,IT1,Bologna Football Club 1909,400000.0,6000000.0
3579,42205,Yann,Sommer,Yann Sommer,2025,46,yann-sommer,Switzerland,Morges,Switzerland,...,NaN,https://img.a.transfermarkt.technology/portrai...,94.0,0.0,NaN,https://www.transfermarkt.co.uk/yann-sommer/pr...,IT1,Football Club Internazionale Milano S.p.A.,2500000.0,13000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46188,1259706,Henrique,Menke,Henrique Menke,2025,1047,henrique-menke,Brazil,Balneário Camboriú,Brazil,...,N29,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,NaN,https://www.transfermarkt.co.uk/henrique-menke...,IT1,Calcio Como,NaN,NaN
46606,1300966,Branimir,Mlacic,Branimir Mlacic,2025,410,branimir-mlacic,Croatia,Split,Croatia,...,LIAN Sports Group,https://img.a.transfermarkt.technology/portrai...,3.0,1.0,NaN,https://www.transfermarkt.co.uk/branimir-mlaci...,IT1,Udinese Calcio,NaN,NaN
46768,1315458,Fallou,Cham,Fallou Cham,2025,276,fallou-cham,NaN,NaN,The Gambia,...,Dream and Goal,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/fallou-cham/pr...,IT1,Verona Hellas Football Club,NaN,NaN
46959,1355285,NaN,Arthur Borghi,Arthur Borghi,2025,276,arthur-borghi,Brazil,Campo Mourão,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/arthur-borghi/...,IT1,Verona Hellas Football Club,NaN,NaN
47119,1371793,Paul,Mendy,Paul Mendy,2025,1390,paul-mendy,Senegal,Rufisque,Senegal,...,Dream and Goal,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/paul-mendy/pro...,IT1,Cagliari Calcio,NaN,NaN

In [3]:
teams = pd.read_csv('tables/clubs.csv')
seriea_teams = teams[(teams.domestic_competition_id == 'IT1') & (teams.last_season > 2024)]
seriea_teams

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
4,1005,us-lecce,Unione Sportiva Lecce,IT1,NaN,27,25.3,23,85.2,13,Ettore Giardiniero,31559,+€8.62m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...
12,1025,fc-bologna,Bologna Football Club 1909,IT1,NaN,27,27.4,17,63.0,11,Stadio Renato Dall’Ara,36462,+€27.70m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-bologna/sta...
21,1047,como-1907,Calcio Como,IT1,NaN,27,26.4,25,92.6,10,Giuseppe Sinigaglia,12039,€-110.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/como-1907/star...
87,12,as-rom,Associazione Sportiva Roma,IT1,NaN,27,26.3,19,70.4,13,Olimpico di Roma,70634,€-24.45m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
115,130,parma-calcio-1913,Parma Calcio 1913,IT1,NaN,25,24.7,19,76.0,2,Ennio Tardini,22352,+€42.29m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/parma-calcio-1...
126,1390,cagliari-calcio,Cagliari Calcio,IT1,NaN,29,25.6,14,48.3,6,Unipol Domus,16416,+€800k,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/cagliari-calci...
236,2239,us-cremonese,Unione Sportiva Cremonese S.p.A.,IT1,NaN,27,28.6,12,44.4,3,Giovanni Zini,16003,€-17.75m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-cremonese/s...
291,252,genua-cfc,Genoa Cricket and Football Club,IT1,NaN,26,26.8,18,69.2,8,Luigi Ferraris,34901,+€47.93m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/genua-cfc/star...
326,276,hellas-verona,Verona Hellas Football Club,IT1,NaN,30,26.0,26,86.7,9,Marcantonio Bentegodi,39211,+€7.30m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/hellas-verona/...
467,398,lazio-rom,Società Sportiva Lazio S.p.A.,IT1,NaN,28,27.8,17,60.7,11,Olimpico di Roma,70634,+€13.55m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/lazio-rom/star...
484,410,udinese-calcio,Udinese Calcio,IT1,NaN,26,26.3,21,80.8,8,Bluenergy Stadium,25144,+€47.65m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/udinese-calcio...
493,416,fc-turin,Torino Calcio,IT1,NaN,30,26.4,24,80.0,10,Olimpico Grande Torino,28177,+€21.84m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-turin/start...
496,4172,ac-pisa-1909,Pisa Sporting Club,IT1,NaN,29,27.2,21,72.4,7,Cetilar® Arena,12508,€-29.90m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ac-pisa-1909/s...
505,430,ac-florenz,Associazione Calcio Fiorentina,IT1,NaN,27,26.1,11,40.7,9,Artemio Franchi,43147,€-29.21m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ac-florenz/sta...
525,46,inter-mailand,Football Club Internazionale Milano S.p.A.,IT1,NaN,24,29.5,16,66.7,15,Giuseppe Meazza,75923,€-48.35m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/inter-mailand/...
548,5,ac-mailand,Associazione Calcio Milan,IT1,NaN,23,27.4,18,78.3,19,Giuseppe Meazza,75923,+€6.00m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ac-mailand/sta...
553,506,juventus-turin,Juventus Football Club,IT1,NaN,25,27.5,18,72.0,18,Allianz Stadium,41507,€-48.75m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/juventus-turin...
617,6195,ssc-neapel,Società Sportiva Calcio Napoli,IT1,NaN,26,28.8,17,65.4,16,Diego Armando Maradona,54726,€-15.35m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ssc-neapel/sta...
641,6574,us-sassuolo,Unione Sportiva Sassuolo Calcio,IT1,NaN,29,26.1,18,62.1,12,Mapei Stadium - Città del Tricolore,21584,€-34.63m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-sassuolo/st...
714,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,24,27.5,14,58.3,18,New Balance Arena - Bergamo,24950,€-8.28m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/atalanta-berga...

In [4]:
ratings = pd.read_csv('tables/player_valuations.csv')
ratings

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057,BE1
1,342216,2001-07-20,100000,Unknown,1241,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126,TR1
3,6893,2003-12-15,900000,Galatasaray,984,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398,IT1
...,...,...,...,...,...,...
507810,922783,2026-01-24,25000,Asteras Aktor B,120649,NaN
507811,1175508,2026-01-29,50000,Eyüpspor,7160,TR1
507812,439343,2026-02-11,1200000,Johor Darul Ta'zim,15817,NaN
507813,1133978,2026-02-13,250000,FC Lausanne-Sport,527,C1
507814,836132,2026-02-27,10000,ASC Jaraaf de Dakar,3917,NaN

In [35]:
events = pd.read_csv('tables/game_events.csv')
ids = seriea_players.player_id
ids.count()
events.count()

game_event_id       1272163
date                1272163
game_id             1272163
minute              1272163
type                1272163
club_id             1272163
club_name           1272163
player_id           1272163
description         1178991
player_in_id         629147
player_assist_id     187911
dtype: int64

In [36]:
mask = events["player_id"].isin(ids)
events["date"] = pd.to_datetime(events["date"])
relevant_events = events[mask & (events.date.dt.year > 2021)]
relevant_events

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
672327,8bb75f6b8785edbb8ad60d44ec1ee1c1,2022-02-20,3580287,33,Cards,1053,Aalborg BK,543822,4. Yellow card,NaN,NaN
672383,11fbbc3448a3d22d923b16236ce2e114,2022-02-18,3580291,78,Cards,5817,Sönderjyske,496745,"5. Yellow card , Foul",NaN,NaN
672437,156c160c0d7f0053a22c356cfba34a4c,2022-02-27,3580314,46,Substitutions,1053,Aalborg BK,543822,", Tactical",247909.0,NaN
672452,c0b6fad4666d95dfa59c86acd709ebf3,2022-02-27,3580315,80,Substitutions,865,FC Midtjylland,462823,", Tactical",590835.0,NaN
672511,10567d382199d5228172b9caee0f0c69,2022-03-04,3580319,72,Substitutions,865,FC Midtjylland,462823,", Tactical",18829.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1270456,2f55177cd8e3be679b81b003b48c32b4,2026-05-13,4869248,77,Substitutions,46,Inter Milan,406625,", Tactical",827734.0,NaN
1270457,0bc2a1a8c99a5f3dc69c5c7deb17ebc3,2026-05-13,4869248,6,Cards,46,Inter Milan,441986,"1. Yellow card , Foul",NaN,NaN
1270458,d597922b412376b51ae133959d6b6326,2026-05-13,4869248,66,Substitutions,398,SS Lazio,462823,", Tactical",550106.0,NaN
1270459,da67584aab0b248031bf9c7e48707ccb,2026-05-13,4869248,38,Cards,398,SS Lazio,618341,"2. Yellow card , Foul",NaN,NaN
1270460,cc1c2edac21f1b573fa1a9cea9d1947c,2026-05-13,4869248,68,Substitutions,46,Inter Milan,668207,", Tactical",55735.0,NaN

In [37]:
relevant_events = relevant_events.merge(
    seriea_players[["player_id", "name"]],
    on="player_id",
    how="left"
)
relevant_events

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id,name
0,8bb75f6b8785edbb8ad60d44ec1ee1c1,2022-02-20,3580287,33,Cards,1053,Aalborg BK,543822,4. Yellow card,NaN,NaN,Malthe Højholt
1,11fbbc3448a3d22d923b16236ce2e114,2022-02-18,3580291,78,Cards,5817,Sönderjyske,496745,"5. Yellow card , Foul",NaN,NaN,Emil Holm
2,156c160c0d7f0053a22c356cfba34a4c,2022-02-27,3580314,46,Substitutions,1053,Aalborg BK,543822,", Tactical",247909.0,NaN,Malthe Højholt
3,c0b6fad4666d95dfa59c86acd709ebf3,2022-02-27,3580315,80,Substitutions,865,FC Midtjylland,462823,", Tactical",590835.0,NaN,Gustav Isaksen
4,10567d382199d5228172b9caee0f0c69,2022-03-04,3580319,72,Substitutions,865,FC Midtjylland,462823,", Tactical",18829.0,NaN,Gustav Isaksen
...,...,...,...,...,...,...,...,...,...,...,...,...
27758,2f55177cd8e3be679b81b003b48c32b4,2026-05-13,4869248,77,Substitutions,46,Inter Milan,406625,", Tactical",827734.0,NaN,Lautaro Martínez
27759,0bc2a1a8c99a5f3dc69c5c7deb17ebc3,2026-05-13,4869248,6,Cards,46,Inter Milan,441986,"1. Yellow card , Foul",NaN,NaN,Yann Bisseck
27760,d597922b412376b51ae133959d6b6326,2026-05-13,4869248,66,Substitutions,398,SS Lazio,462823,", Tactical",550106.0,NaN,Gustav Isaksen
27761,da67584aab0b248031bf9c7e48707ccb,2026-05-13,4869248,38,Cards,398,SS Lazio,618341,"2. Yellow card , Foul",NaN,NaN,Mario Gila
27762,cc1c2edac21f1b573fa1a9cea9d1947c,2026-05-13,4869248,68,Substitutions,46,Inter Milan,668207,", Tactical",55735.0,NaN,Petar Sučić