# serieA-Predicition-Model

## Importazione delle librerie

In questa sezione vengono importate le librerie principali utilizzate per l'analisi dei dati.

- `pandas` viene utilizzata per caricare, filtrare e manipolare i dataset in formato tabellare.
- `numpy` viene utilizzata per operazioni numeriche e gestione di array.

## Caricamento e selezione dei giocatori di Serie A

Il file `players.csv` contiene informazioni anagrafiche e sportive sui calciatori presenti nel dataset.

In questa fase vengono selezionati soltanto i giocatori appartenenti alla competizione italiana, identificata dal codice `IT1`, corrispondente alla Serie A.

Inoltre, vengono mantenuti solo i giocatori con `last_season` successiva al 2024, in modo da lavorare sui calciatori più recenti e coerenti con l'obiettivo di predire il campionato attuale.

Infine, viene salvato l'elenco degli identificativi dei giocatori selezionati nella variabile `ids`.

In [1]:
import pandas as pd
import numpy as np

In [2]:
players = pd.read_csv('tables/players.csv')
seriea_players = players[(players.current_club_domestic_competition_id == 'IT1') & (players.last_season > 2024)]
ids = seriea_players.player_id
seriea_players

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
1299,15452,Raúl,Albiol,Raúl Albiol,2025,4172,raul-albiol,Spain,Vilamarxant,Spain,...,LP Sport Management,https://img.a.transfermarkt.technology/portrai...,58.0,0.0,NaN,https://www.transfermarkt.co.uk/raul-albiol/pr...,IT1,Pisa Sporting Club,800000.0,18000000.0
2342,27807,Daniele,Padelli,Daniele Padelli,2025,410,daniele-padelli,Italy,Lecco,Italy,...,Mondial,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,NaN,https://www.transfermarkt.co.uk/daniele-padell...,IT1,Udinese Calcio,150000.0,2000000.0
2354,27992,Luka,Modrić,Luka Modrić,2025,5,luka-modric,Jugoslawien (SFR),Zadar,Croatia,...,NaN,https://img.a.transfermarkt.technology/portrai...,198.0,29.0,NaN,https://www.transfermarkt.co.uk/luka-modric/pr...,IT1,Associazione Calcio Milan,4000000.0,55000000.0
2757,33571,Lorenzo,De Silvestri,Lorenzo De Silvestri,2025,1025,lorenzo-de-silvestri,Italy,Roma,Italy,...,Sergio Berti,https://img.a.transfermarkt.technology/portrai...,6.0,0.0,NaN,https://www.transfermarkt.co.uk/lorenzo-de-sil...,IT1,Bologna Football Club 1909,400000.0,6000000.0
3579,42205,Yann,Sommer,Yann Sommer,2025,46,yann-sommer,Switzerland,Morges,Switzerland,...,NaN,https://img.a.transfermarkt.technology/portrai...,94.0,0.0,NaN,https://www.transfermarkt.co.uk/yann-sommer/pr...,IT1,Football Club Internazionale Milano S.p.A.,2500000.0,13000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46188,1259706,Henrique,Menke,Henrique Menke,2025,1047,henrique-menke,Brazil,Balneário Camboriú,Brazil,...,N29,https://img.a.transfermarkt.technology/portrai...,0.0,0.0,NaN,https://www.transfermarkt.co.uk/henrique-menke...,IT1,Calcio Como,NaN,NaN
46606,1300966,Branimir,Mlacic,Branimir Mlacic,2025,410,branimir-mlacic,Croatia,Split,Croatia,...,LIAN Sports Group,https://img.a.transfermarkt.technology/portrai...,3.0,1.0,NaN,https://www.transfermarkt.co.uk/branimir-mlaci...,IT1,Udinese Calcio,NaN,NaN
46768,1315458,Fallou,Cham,Fallou Cham,2025,276,fallou-cham,NaN,NaN,The Gambia,...,Dream and Goal,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/fallou-cham/pr...,IT1,Verona Hellas Football Club,NaN,NaN
46959,1355285,NaN,Arthur Borghi,Arthur Borghi,2025,276,arthur-borghi,Brazil,Campo Mourão,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/arthur-borghi/...,IT1,Verona Hellas Football Club,NaN,NaN
47119,1371793,Paul,Mendy,Paul Mendy,2025,1390,paul-mendy,Senegal,Rufisque,Senegal,...,Dream and Goal,https://img.a.transfermarkt.technology/portrai...,NaN,NaN,NaN,https://www.transfermarkt.co.uk/paul-mendy/pro...,IT1,Cagliari Calcio,NaN,NaN

## Caricamento e selezione delle squadre di Serie A

In questa sezione viene caricato il file `clubs.csv`, che contiene informazioni relative alle società calcistiche presenti nel dataset.

Il dataset viene filtrato mantenendo soltanto le squadre appartenenti alla competizione italiana di Serie A, identificata dal codice `IT1`.

Inoltre, vengono considerate solo le squadre con `last_season` maggiore di 2024, in modo da selezionare i club presenti nella stagione più recente del campionato.

Le variabili contenute in questa tabella infatti permettono di descrivere caratteristiche delle squadre.

In [3]:
teams = pd.read_csv('tables/clubs.csv')
seriea_teams = teams[(teams.domestic_competition_id == 'IT1') & (teams.last_season > 2024)]
seriea_teams

,club_id,club_code,name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url
4,1005,us-lecce,Unione Sportiva Lecce,IT1,NaN,27,25.3,23,85.2,13,Ettore Giardiniero,31559,+€8.62m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-lecce/start...
12,1025,fc-bologna,Bologna Football Club 1909,IT1,NaN,27,27.4,17,63.0,11,Stadio Renato Dall’Ara,36462,+€27.70m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-bologna/sta...
21,1047,como-1907,Calcio Como,IT1,NaN,27,26.4,25,92.6,10,Giuseppe Sinigaglia,12039,€-110.51m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/como-1907/star...
87,12,as-rom,Associazione Sportiva Roma,IT1,NaN,27,26.3,19,70.4,13,Olimpico di Roma,70634,€-24.45m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/as-rom/startse...
115,130,parma-calcio-1913,Parma Calcio 1913,IT1,NaN,25,24.7,19,76.0,2,Ennio Tardini,22352,+€42.29m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/parma-calcio-1...
126,1390,cagliari-calcio,Cagliari Calcio,IT1,NaN,29,25.6,14,48.3,6,Unipol Domus,16416,+€800k,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/cagliari-calci...
236,2239,us-cremonese,Unione Sportiva Cremonese S.p.A.,IT1,NaN,27,28.6,12,44.4,3,Giovanni Zini,16003,€-17.75m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-cremonese/s...
291,252,genua-cfc,Genoa Cricket and Football Club,IT1,NaN,26,26.8,18,69.2,8,Luigi Ferraris,34901,+€47.93m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/genua-cfc/star...
326,276,hellas-verona,Verona Hellas Football Club,IT1,NaN,30,26.0,26,86.7,9,Marcantonio Bentegodi,39211,+€7.30m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/hellas-verona/...
467,398,lazio-rom,Società Sportiva Lazio S.p.A.,IT1,NaN,28,27.8,17,60.7,11,Olimpico di Roma,70634,+€13.55m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/lazio-rom/star...
484,410,udinese-calcio,Udinese Calcio,IT1,NaN,26,26.3,21,80.8,8,Bluenergy Stadium,25144,+€47.65m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/udinese-calcio...
493,416,fc-turin,Torino Calcio,IT1,NaN,30,26.4,24,80.0,10,Olimpico Grande Torino,28177,+€21.84m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/fc-turin/start...
496,4172,ac-pisa-1909,Pisa Sporting Club,IT1,NaN,29,27.2,21,72.4,7,Cetilar® Arena,12508,€-29.90m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ac-pisa-1909/s...
505,430,ac-florenz,Associazione Calcio Fiorentina,IT1,NaN,27,26.1,11,40.7,9,Artemio Franchi,43147,€-29.21m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ac-florenz/sta...
525,46,inter-mailand,Football Club Internazionale Milano S.p.A.,IT1,NaN,24,29.5,16,66.7,15,Giuseppe Meazza,75923,€-48.35m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/inter-mailand/...
548,5,ac-mailand,Associazione Calcio Milan,IT1,NaN,23,27.4,18,78.3,19,Giuseppe Meazza,75923,+€6.00m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ac-mailand/sta...
553,506,juventus-turin,Juventus Football Club,IT1,NaN,25,27.5,18,72.0,18,Allianz Stadium,41507,€-48.75m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/juventus-turin...
617,6195,ssc-neapel,Società Sportiva Calcio Napoli,IT1,NaN,26,28.8,17,65.4,16,Diego Armando Maradona,54726,€-15.35m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/ssc-neapel/sta...
641,6574,us-sassuolo,Unione Sportiva Sassuolo Calcio,IT1,NaN,29,26.1,18,62.1,12,Mapei Stadium - Città del Tricolore,21584,€-34.63m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/us-sassuolo/st...
714,800,atalanta-bergamo,Atalanta Bergamasca Calcio S.p.a.,IT1,NaN,24,27.5,14,58.3,18,New Balance Arena - Bergamo,24950,€-8.28m,NaN,2025,../data/raw/transfermarkt-scraper/2025/clubs.j...,https://www.transfermarkt.co.uk/atalanta-berga...

## Selezione delle ultime valutazioni di mercato dei giocatori

In questa sezione viene caricato il file `player_valuations.csv`, che contiene le valutazioni di mercato dei giocatori nel tempo.

Poiché ogni giocatore può avere più valutazioni associate a date diverse, il dataset viene prima filtrato mantenendo soltanto i giocatori di Serie A selezionati in precedenza.

Successivamente, la colonna `date` viene convertita in formato datetime, così da poter ordinare e confrontare correttamente le date delle valutazioni.

Per ogni giocatore viene poi selezionata soltanto la valutazione più recente disponibile.

In [4]:
ratings = pd.read_csv('tables/player_valuations.csv')
ratings["date"] = pd.to_datetime(ratings['date'])
relevant_ratings = ratings[(ratings.player_id.isin(ids))]
latest_ratings = relevant_ratings.loc[
    relevant_ratings.groupby("player_id")["date"].idxmax()
]
latest_ratings

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
507005,15452,2025-12-23,800000,Pisa Sporting Club,4172,IT1
507006,27807,2025-12-23,150000,Udinese Calcio,410,IT1
507007,27992,2025-12-23,4000000,AC Milan,5,IT1
481466,33571,2024-06-05,400000,Bologna FC 1909,1025,IT1
507008,42205,2025-12-23,2500000,Inter Milan,46,IT1
...,...,...,...,...,...,...
503737,1083069,2025-12-10,700000,Clube Atlético Mineiro,276,IT1
485550,1111820,2024-06-25,150000,Hellas Verona Primavera,276,IT1
507383,1112449,2025-12-23,15000000,US Lecce,1005,IT1
504861,1131161,2025-12-15,10000000,Olympique Marseille,12,IT1
507384,1190411,2025-12-23,30000000,Como 1907,1047,IT1

In [5]:
np.array_equal(latest_ratings["market_value_in_eur"].values, (seriea_players.market_value_in_eur[~seriea_players.market_value_in_eur.isna()].values))

True

In [6]:
events = pd.read_csv('tables/game_events.csv')

## Selezione degli eventi rilevanti

In questa sezione vengono selezionati gli eventi di gioco associati ai giocatori di Serie A.

Il filtro viene costruito verificando se il `player_id` presente nella tabella degli eventi appartiene all'elenco `ids`, che contiene gli identificativi dei giocatori selezionati dalla tabella `players.csv`.

La colonna `date` viene convertita in formato datetime, così da poter applicare correttamente un filtro temporale.

Infine, vengono mantenuti solo gli eventi successivi al 2021, in modo da concentrare l'analisi sugli anni più recenti.

In [7]:
mask = events["player_id"].isin(ids)
events["date"] = pd.to_datetime(events["date"])
relevant_events = events[mask & (events.date.dt.year > 2020)]
relevant_events

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
576638,a4af19d9418e14a3c9864d35808c0760,2021-06-11,3287199,85,Substitutions,3376,Italy,177843,", Injury",197300.0,NaN
576640,426a7c534adc738a9b70c7d6d7c30377,2021-06-11,3287199,74,Substitutions,3376,Italy,265088,", Tactical",199248.0,NaN
576657,ca77d03879224f952572075b0c762e30,2021-06-12,3287201,10,Goals,3382,Belgium,96341,", Left-footed shot, 1. Tournament Goal Assist:...",NaN,56416.0
576658,065757152757dbebf3752851a2a0c055,2021-06-12,3287201,88,Goals,3382,Belgium,96341,", Right-footed shot, 2. Tournament Goal Assist...",NaN,100986.0
576689,492b5f64bbd2e0ea6be550f82da8f65e,2021-06-13,3287203,85,Goals,3379,Netherlands,321528,", Header, 1. Tournament Goal Assist: , Cross, ...",NaN,177476.0
...,...,...,...,...,...,...,...,...,...,...,...
1270456,2f55177cd8e3be679b81b003b48c32b4,2026-05-13,4869248,77,Substitutions,46,Inter Milan,406625,", Tactical",827734.0,NaN
1270457,0bc2a1a8c99a5f3dc69c5c7deb17ebc3,2026-05-13,4869248,6,Cards,46,Inter Milan,441986,"1. Yellow card , Foul",NaN,NaN
1270458,d597922b412376b51ae133959d6b6326,2026-05-13,4869248,66,Substitutions,398,SS Lazio,462823,", Tactical",550106.0,NaN
1270459,da67584aab0b248031bf9c7e48707ccb,2026-05-13,4869248,38,Cards,398,SS Lazio,618341,"2. Yellow card , Foul",NaN,NaN
1270460,cc1c2edac21f1b573fa1a9cea9d1947c,2026-05-13,4869248,68,Substitutions,46,Inter Milan,668207,", Tactical",55735.0,NaN

## Collegamento tra eventi e giocatori

In questa fase il dataset degli eventi viene collegato alla tabella dei giocatori di Serie A.

Il collegamento viene effettuato tramite la variabile `player_id`, presente sia nella tabella degli eventi sia nella tabella dei giocatori.

L'obiettivo è arricchire il dataset degli eventi aggiungendo il nome del giocatore coinvolto in ciascun evento. In questo modo la tabella diventa più leggibile e più semplice da interpretare durante l'analisi esplorativa.

In [8]:
relevant_events = relevant_events.merge(
    seriea_players[["player_id", "name"]],
    on="player_id",
    how="left"
)
relevant_events

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id,name
0,a4af19d9418e14a3c9864d35808c0760,2021-06-11,3287199,85,Substitutions,3376,Italy,177843,", Injury",197300.0,NaN,Domenico Berardi
1,426a7c534adc738a9b70c7d6d7c30377,2021-06-11,3287199,74,Substitutions,3376,Italy,265088,", Tactical",199248.0,NaN,Manuel Locatelli
2,ca77d03879224f952572075b0c762e30,2021-06-12,3287201,10,Goals,3382,Belgium,96341,", Left-footed shot, 1. Tournament Goal Assist:...",NaN,56416.0,Romelu Lukaku
3,065757152757dbebf3752851a2a0c055,2021-06-12,3287201,88,Goals,3382,Belgium,96341,", Right-footed shot, 2. Tournament Goal Assist...",NaN,100986.0,Romelu Lukaku
4,492b5f64bbd2e0ea6be550f82da8f65e,2021-06-13,3287203,85,Goals,3379,Netherlands,321528,", Header, 1. Tournament Goal Assist: , Cross, ...",NaN,177476.0,Denzel Dumfries
...,...,...,...,...,...,...,...,...,...,...,...,...
32394,2f55177cd8e3be679b81b003b48c32b4,2026-05-13,4869248,77,Substitutions,46,Inter Milan,406625,", Tactical",827734.0,NaN,Lautaro Martínez
32395,0bc2a1a8c99a5f3dc69c5c7deb17ebc3,2026-05-13,4869248,6,Cards,46,Inter Milan,441986,"1. Yellow card , Foul",NaN,NaN,Yann Bisseck
32396,d597922b412376b51ae133959d6b6326,2026-05-13,4869248,66,Substitutions,398,SS Lazio,462823,", Tactical",550106.0,NaN,Gustav Isaksen
32397,da67584aab0b248031bf9c7e48707ccb,2026-05-13,4869248,38,Cards,398,SS Lazio,618341,"2. Yellow card , Foul",NaN,NaN,Mario Gila
32398,cc1c2edac21f1b573fa1a9cea9d1947c,2026-05-13,4869248,68,Substitutions,46,Inter Milan,668207,", Tactical",55735.0,NaN,Petar Sučić

In [9]:
games = pd.read_csv('tables/games.csv')
relevant_games = games[(games.competition_id == 'IT1') & (games.season > 2020)]
relevant_games.drop(['competition_type', 'home_club_formation', 'away_club_formation', 'url', 'referee', 'home_club_manager_name', 'away_club_manager_name', 'competition_id'], axis='columns')

,game_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,stadium,attendance,home_club_name,away_club_name,aggregate
54640,3614505,2021,1. Matchday,2021-08-22,1025,380,3,2,6.0,13.0,Stadio Renato Dall’Ara,8375.0,Bologna Football Club 1909,US Salernitana 1919,3:2
54641,3614506,2021,1. Matchday,2021-08-23,1390,3522,2,2,9.0,11.0,Unipol Domus,5387.0,Cagliari Calcio,Spezia Calcio,2:2
54642,3614507,2021,1. Matchday,2021-08-21,749,398,1,3,18.0,3.0,Carlo Castellani,3655.0,FC Empoli,Società Sportiva Lazio S.p.A.,1:3
54643,3614508,2021,1. Matchday,2021-08-21,276,6574,2,3,14.0,5.0,Marcantonio Bentegodi,5448.0,Verona Hellas Football Club,Unione Sportiva Sassuolo Calcio,2:3
54644,3614509,2021,1. Matchday,2021-08-21,46,252,4,0,1.0,20.0,Giuseppe Meazza,27402.0,Football Club Internazionale Milano S.p.A.,Genoa Cricket and Football Club,4:0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79666,4621093,2025,38. Matchday,2026-05-24,5,1390,1,2,5.0,14.0,Giuseppe Meazza,74539.0,Associazione Calcio Milan,Cagliari Calcio,1:2
79667,4621094,2025,38. Matchday,2026-05-24,6195,410,1,0,2.0,10.0,Diego Armando Maradona,50000.0,Società Sportiva Calcio Napoli,Udinese Calcio,1:0
79668,4621095,2025,38. Matchday,2026-05-24,130,6574,1,0,13.0,11.0,Ennio Tardini,17369.0,Parma Calcio 1913,Unione Sportiva Sassuolo Calcio,1:0
79669,4621096,2025,38. Matchday,2026-05-24,416,506,2,2,12.0,6.0,Olimpico Grande Torino,26000.0,Torino Calcio,Juventus Football Club,2:2
79670,4621097,2025,38. Matchday,2026-05-24,276,12,0,2,19.0,3.0,Marcantonio Bentegodi,23277.0,Verona Hellas Football Club,Associazione Sportiva Roma,0:2

In [10]:
seriea_teams.drop(['club_code', 'domestic_competition_id', 'stadium_name', 'last_season', 'filename', 'url', 'coach_name'], axis='columns')

,club_id,name,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_seats,net_transfer_record
4,1005,Unione Sportiva Lecce,NaN,27,25.3,23,85.2,13,31559,+€8.62m
12,1025,Bologna Football Club 1909,NaN,27,27.4,17,63.0,11,36462,+€27.70m
21,1047,Calcio Como,NaN,27,26.4,25,92.6,10,12039,€-110.51m
87,12,Associazione Sportiva Roma,NaN,27,26.3,19,70.4,13,70634,€-24.45m
115,130,Parma Calcio 1913,NaN,25,24.7,19,76.0,2,22352,+€42.29m
126,1390,Cagliari Calcio,NaN,29,25.6,14,48.3,6,16416,+€800k
236,2239,Unione Sportiva Cremonese S.p.A.,NaN,27,28.6,12,44.4,3,16003,€-17.75m
291,252,Genoa Cricket and Football Club,NaN,26,26.8,18,69.2,8,34901,+€47.93m
326,276,Verona Hellas Football Club,NaN,30,26.0,26,86.7,9,39211,+€7.30m
467,398,Società Sportiva Lazio S.p.A.,NaN,28,27.8,17,60.7,11,70634,+€13.55m
484,410,Udinese Calcio,NaN,26,26.3,21,80.8,8,25144,+€47.65m
493,416,Torino Calcio,NaN,30,26.4,24,80.0,10,28177,+€21.84m
496,4172,Pisa Sporting Club,NaN,29,27.2,21,72.4,7,12508,€-29.90m
505,430,Associazione Calcio Fiorentina,NaN,27,26.1,11,40.7,9,43147,€-29.21m
525,46,Football Club Internazionale Milano S.p.A.,NaN,24,29.5,16,66.7,15,75923,€-48.35m
548,5,Associazione Calcio Milan,NaN,23,27.4,18,78.3,19,75923,+€6.00m
553,506,Juventus Football Club,NaN,25,27.5,18,72.0,18,41507,€-48.75m
617,6195,Società Sportiva Calcio Napoli,NaN,26,28.8,17,65.4,16,54726,€-15.35m
641,6574,Unione Sportiva Sassuolo Calcio,NaN,29,26.1,18,62.1,12,21584,€-34.63m
714,800,Atalanta Bergamasca Calcio S.p.a.,NaN,24,27.5,14,58.3,18,24950,€-8.28m

In questa fase viene calcolato il valore complessivo della rosa di ogni squadra.

Il dataframe `latest_ratings` contiene, per ogni giocatore selezionato, la sua valutazione di mercato più recente e il club di appartenenza.  
Attraverso il metodo `groupby`, i giocatori vengono raggruppati in base alla squadra, identificata da `current_club_id`.

Per ogni gruppo, cioè per ogni squadra, viene poi calcolata la somma della variabile `latest_market_value`.  
Il risultato rappresenta il valore totale stimato della rosa della squadra.

In [11]:
latest_ratings_clean = latest_ratings[[
    "player_id",
    "market_value_in_eur",
    "date"
]].rename(columns={
    "market_value_in_eur": "latest_market_value",
    "date": "valuation_date"
})

players_values = seriea_players.merge(
    latest_ratings_clean,
    on="player_id"
)

team_values = players_values.groupby(

    "current_club_id",
    as_index=False
)["latest_market_value"].sum()

clubs = pd.read_csv("tables/clubs.csv")

team_values = team_values.merge(
    seriea_teams[["club_id", "name"]],
    left_on="current_club_id",
    right_on="club_id",
    how="inner"
)

team_values

,current_club_id,latest_market_value,club_id,name
0,5,555010000,5,Associazione Calcio Milan
1,12,351800000,12,Associazione Sportiva Roma
2,46,622800000,46,Football Club Internazionale Milano S.p.A.
3,130,102350000,130,Parma Calcio 1913
4,252,111100000,252,Genoa Cricket and Football Club
5,276,91150000,276,Verona Hellas Football Club
6,398,209850000,398,Società Sportiva Lazio S.p.A.
7,410,108900000,410,Udinese Calcio
8,416,139775000,416,Torino Calcio
9,430,275550000,430,Associazione Calcio Fiorentina
10,506,587700000,506,Juventus Football Club
11,800,373175000,800,Atalanta Bergamasca Calcio S.p.a.
12,1005,86225000,1005,Unione Sportiva Lecce
13,1025,207700000,1025,Bologna Football Club 1909
14,1047,262750000,1047,Calcio Como
15,1390,87950000,1390,Cagliari Calcio
16,2239,77125000,2239,Unione Sportiva Cremonese S.p.A.
17,4172,56050000,4172,Pisa Sporting Club
18,6195,395275000,6195,Società Sportiva Calcio Napoli
19,6574,129750000,6574,Unione Sportiva Sassuolo Calcio

In [12]:
games_specs = pd.DataFrame(relevant_games[['season', 'home_club_id', 'away_club_id', 'home_club_name', 'away_club_name', 'home_club_goals', 'away_club_goals']])

In [13]:
home_goals = games_specs[['season', 'home_club_name', 'home_club_goals']].groupby(['season', 'home_club_name']).sum().reset_index()
away_goals = games_specs[['season', 'away_club_name', 'away_club_goals']].groupby(['season', 'away_club_name']).sum().reset_index()
goals = home_goals.merge(away_goals, left_on=['season', 'home_club_name'], right_on=['season', 'away_club_name'])
goals = goals.drop('away_club_name', axis='columns')
goals['goals'] = goals['away_club_goals'] + goals['home_club_goals']
goals

,season,home_club_name,home_club_goals,away_club_goals,goals
0,2021,Associazione Calcio Fiorentina,38,21,59
1,2021,Associazione Calcio Milan,28,41,69
2,2021,Associazione Sportiva Roma,26,33,59
3,2021,Atalanta Bergamasca Calcio S.p.a.,31,34,65
4,2021,Bologna Football Club 1909,25,19,44
...,...,...,...,...,...
95,2025,Udinese Calcio,18,27,45
96,2025,Unione Sportiva Cremonese S.p.A.,18,14,32
97,2025,Unione Sportiva Lecce,13,15,28
98,2025,Unione Sportiva Sassuolo Calcio,25,21,46
99,2025,Verona Hellas Football Club,12,13,25

In [14]:
points = games_specs[['season', 'home_club_name', 'away_club_name', 'home_club_goals', 'away_club_goals']]
points['home_club_points'] = None
points['away_club_points'] = None
vittorie = points.home_club_goals > points.away_club_goals
pareggi = points.home_club_goals == points.away_club_goals
sconfitte = points.home_club_goals < points.away_club_goals
points.loc[vittorie, 'home_club_points'] = 3
points.loc[vittorie, 'away_club_points'] = 0
points.loc[pareggi, 'home_club_points'] = 1
points.loc[pareggi, 'away_club_points'] = 1
points.loc[sconfitte, 'home_club_points'] = 0
points.loc[sconfitte, 'away_club_points'] = 3
points

,season,home_club_name,away_club_name,home_club_goals,away_club_goals,home_club_points,away_club_points
54640,2021,Bologna Football Club 1909,US Salernitana 1919,3,2,3,0
54641,2021,Cagliari Calcio,Spezia Calcio,2,2,1,1
54642,2021,FC Empoli,Società Sportiva Lazio S.p.A.,1,3,0,3
54643,2021,Verona Hellas Football Club,Unione Sportiva Sassuolo Calcio,2,3,0,3
54644,2021,Football Club Internazionale Milano S.p.A.,Genoa Cricket and Football Club,4,0,3,0
...,...,...,...,...,...,...,...
79666,2025,Associazione Calcio Milan,Cagliari Calcio,1,2,0,3
79667,2025,Società Sportiva Calcio Napoli,Udinese Calcio,1,0,3,0
79668,2025,Parma Calcio 1913,Unione Sportiva Sassuolo Calcio,1,0,3,0
79669,2025,Torino Calcio,Juventus Football Club,2,2,1,1
79670,2025,Verona Hellas Football Club,Associazione Sportiva Roma,0,2,0,3

In [16]:
points['home_club_points'] = points['home_club_points'].astype(int)
points['away_club_points'] = points['away_club_points'].astype(int)
home_points = points[['season', 'home_club_name', 'home_club_points']].groupby(['season', 'home_club_name']).sum().reset_index()
away_points = points[['season', 'away_club_name', 'away_club_points']].groupby(['season', 'away_club_name']).sum().reset_index()
season_points = home_points.merge(away_points, left_on=['season', 'home_club_name'], right_on=['season', 'away_club_name'])
season_points = season_points.drop('away_club_name', axis='columns')
season_points['points'] = season_points['away_club_points'] + season_points['home_club_points']
season_points = season_points.rename(columns={'home_club_points': 'home_points', 'away_club_points': 'away_points'})
season_points

,season,home_club_name,home_points,away_points,points
0,2021,Associazione Calcio Fiorentina,41,21,62
1,2021,Associazione Calcio Milan,40,46,86
2,2021,Associazione Sportiva Roma,36,27,63
3,2021,Atalanta Bergamasca Calcio S.p.a.,20,39,59
4,2021,Bologna Football Club 1909,28,18,46
...,...,...,...,...,...
95,2025,Udinese Calcio,23,27,50
96,2025,Unione Sportiva Cremonese S.p.A.,16,18,34
97,2025,Unione Sportiva Lecce,20,18,38
98,2025,Unione Sportiva Sassuolo Calcio,29,20,49
99,2025,Verona Hellas Football Club,8,13,21